version: 0.1
phases:
  install:
    commands:
      - aws cloudformation package --template-file packaged.yml --s3-bucket photo-album-storage --output-template-file outputsamtemplate.yml
artifacts:
  type: zip
  files:
    - packaged.yml
    - outputsamtemplate.yml
